---

name: CI

on:
  push:
    branches: 
      - kaleidoscope
  schedule:
    - cron: "0 0 * * *" # daily

jobs:

  release:
    runs-on: ubuntu-latest

    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3

      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: "1.12.17"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Packages
        run: npm install

      - name: Build Page
        run: npm run build

